name: Deploy to Cloud Run

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: asclepius-backend
        region: asia-southeast2
        source: .
        env_vars: |
          MODEL_URL=https://storage.googleapis.com/asclepius-bucket-van/model.json
          GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }}
        flags: '--allow-unauthenticated'

    - name: Show output URL
      run: echo "Service URL => ${{ steps.deploy.outputs.url }}"
